/*
 * File: app/view/CarChartsViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.CarChartsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.carcharts',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        carCharts: {
            model: 'CarListings.model.CarChart',
            data: [
                {
                    myField1: 'molestias'
                },
                {
                    myField1: 'perspiciatis'
                },
                {
                    myField1: 'dolore'
                },
                {
                    myField1: 'animi'
                },
                {
                    myField1: 'excepturi'
                },
                {
                    myField1: 'nihil'
                },
                {
                    myField1: 'vitae'
                },
                {
                    myField1: 'iste'
                },
                {
                    myField1: 'officiis'
                },
                {
                    myField1: 'pariatur'
                },
                {
                    myField1: 'odit'
                },
                {
                    myField1: 'repudiandae'
                },
                {
                    myField1: 'voluptates'
                },
                {
                    myField1: 'deserunt'
                },
                {
                    myField1: 'est'
                },
                {
                    myField1: 'nisi'
                },
                {
                    myField1: 'assumenda'
                },
                {
                    myField1: 'aperiam'
                },
                {
                    myField1: 'dolor'
                },
                {
                    myField1: 'ullam'
                },
                {
                    myField1: 'eum'
                },
                {
                    myField1: 'quia'
                },
                {
                    myField1: 'tempore'
                },
                {
                    myField1: 'enim'
                },
                {
                    myField1: 'quisquam'
                },
                {
                    myField1: 'culpa'
                },
                {
                    myField1: 'et'
                },
                {
                    myField1: 'aut'
                },
                {
                    myField1: 'magnam'
                },
                {
                    myField1: 'quia'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});