/*
 * File: app/view/CarDatasViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.CarDatasViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.cardatas',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        carDatas: {
            model: 'CarListings.model.CarData',
            data: [
                {
                    manufacturer: 'possimus',
                    model: 'eos',
                    price: 'voluptas',
                    wiki: 'minima',
                    img: 'praesentium',
                    quality: 'asperiores'
                },
                {
                    manufacturer: 'dolor',
                    model: 'omnis',
                    price: 'corporis',
                    wiki: 'quia',
                    img: 'ut',
                    quality: 'deserunt'
                },
                {
                    manufacturer: 'molestiae',
                    model: 'aliquid',
                    price: 'perferendis',
                    wiki: 'qui',
                    img: 'maxime',
                    quality: 'qui'
                },
                {
                    manufacturer: 'qui',
                    model: 'necessitatibus',
                    price: 'sint',
                    wiki: 'aut',
                    img: 'iste',
                    quality: 'quas'
                },
                {
                    manufacturer: 'error',
                    model: 'dolorem',
                    price: 'beatae',
                    wiki: 'animi',
                    img: 'atque',
                    quality: 'autem'
                },
                {
                    manufacturer: 'ipsam',
                    model: 'facere',
                    price: 'quibusdam',
                    wiki: 'et',
                    img: 'eveniet',
                    quality: 'tempore'
                },
                {
                    manufacturer: 'sequi',
                    model: 'nemo',
                    price: 'autem',
                    wiki: 'deleniti',
                    img: 'et',
                    quality: 'neque'
                },
                {
                    manufacturer: 'in',
                    model: 'est',
                    price: 'provident',
                    wiki: 'ipsam',
                    img: 'recusandae',
                    quality: 'quia'
                },
                {
                    manufacturer: 'voluptas',
                    model: 'fuga',
                    price: 'aut',
                    wiki: 'id',
                    img: 'beatae',
                    quality: 'nihil'
                },
                {
                    manufacturer: 'minima',
                    model: 'alias',
                    price: 'est',
                    wiki: 'adipisci',
                    img: 'et',
                    quality: 'placeat'
                },
                {
                    manufacturer: 'est',
                    model: 'reprehenderit',
                    price: 'voluptas',
                    wiki: 'enim',
                    img: 'culpa',
                    quality: 'est'
                },
                {
                    manufacturer: 'qui',
                    model: 'sed',
                    price: 'itaque',
                    wiki: 'tempora',
                    img: 'dolor',
                    quality: 'ut'
                },
                {
                    manufacturer: 'similique',
                    model: 'voluptatem',
                    price: 'rerum',
                    wiki: 'incidunt',
                    img: 'eaque',
                    quality: 'ea'
                },
                {
                    manufacturer: 'autem',
                    model: 'sint',
                    price: 'earum',
                    wiki: 'illo',
                    img: 'nulla',
                    quality: 'sed'
                },
                {
                    manufacturer: 'dicta',
                    model: 'dolorum',
                    price: 'fuga',
                    wiki: 'dolor',
                    img: 'vero',
                    quality: 'aut'
                },
                {
                    manufacturer: 'quidem',
                    model: 'est',
                    price: 'esse',
                    wiki: 'nesciunt',
                    img: 'aut',
                    quality: 'tenetur'
                },
                {
                    manufacturer: 'illo',
                    model: 'illum',
                    price: 'excepturi',
                    wiki: 'qui',
                    img: 'officiis',
                    quality: 'eos'
                },
                {
                    manufacturer: 'nobis',
                    model: 'repellendus',
                    price: 'rerum',
                    wiki: 'id',
                    img: 'occaecati',
                    quality: 'ipsum'
                },
                {
                    manufacturer: 'tempore',
                    model: 'excepturi',
                    price: 'culpa',
                    wiki: 'tempora',
                    img: 'rerum',
                    quality: 'recusandae'
                },
                {
                    manufacturer: 'et',
                    model: 'commodi',
                    price: 'quaerat',
                    wiki: 'nemo',
                    img: 'sint',
                    quality: 'provident'
                },
                {
                    manufacturer: 'expedita',
                    model: 'nihil',
                    price: 'laboriosam',
                    wiki: 'animi',
                    img: 'impedit',
                    quality: 'dolores'
                },
                {
                    manufacturer: 'deserunt',
                    model: 'neque',
                    price: 'quo',
                    wiki: 'eius',
                    img: 'veniam',
                    quality: 'nam'
                },
                {
                    manufacturer: 'et',
                    model: 'fuga',
                    price: 'quasi',
                    wiki: 'architecto',
                    img: 'sit',
                    quality: 'sequi'
                },
                {
                    manufacturer: 'maiores',
                    model: 'est',
                    price: 'dignissimos',
                    wiki: 'consectetur',
                    img: 'ut',
                    quality: 'et'
                },
                {
                    manufacturer: 'nihil',
                    model: 'ea',
                    price: 'eius',
                    wiki: 'laudantium',
                    img: 'tempora',
                    quality: 'impedit'
                },
                {
                    manufacturer: 'maxime',
                    model: 'qui',
                    price: 'quis',
                    wiki: 'voluptatem',
                    img: 'inventore',
                    quality: 'doloribus'
                },
                {
                    manufacturer: 'officiis',
                    model: 'consequatur',
                    price: 'modi',
                    wiki: 'alias',
                    img: 'sed',
                    quality: 'totam'
                },
                {
                    manufacturer: 'hic',
                    model: 'illo',
                    price: 'vel',
                    wiki: 'possimus',
                    img: 'eligendi',
                    quality: 'inventore'
                },
                {
                    manufacturer: 'et',
                    model: 'consequatur',
                    price: 'officia',
                    wiki: 'quam',
                    img: 'ea',
                    quality: 'odio'
                },
                {
                    manufacturer: 'laborum',
                    model: 'assumenda',
                    price: 'dolore',
                    wiki: 'eius',
                    img: 'ut',
                    quality: 'vero'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});